title: 꿈을 기록하는 Blog
email: useong0830@gmail.com
description: 웹 개발자 이우성의 개발 블로그입니다.
author: useonglee
baseurl: ""
url: "https://useong.github.io"

# Social Profiles
github_username: useonglee
instagram_username: hyeonyeongggg_
# rocket_username: 2247han

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-134593008-1 # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
